### ISSUE TITLE
'myPage' is down with this plugin

### ISSUE THREAD

**Issue by gainskills** [HugoHasenbein/redmine_more_filters#16]
Redmine version: 4.10 + Pg12 + Docker

Another extension installed? : Yes

Extension list:
```
redmine_zenedit
redmine_lightbox2
redmine_issue_templates
redmine_issue_dynamic_edit
redmine_im_link
redmine_more_filters
periodictask
custom_tables
```

Issue:
'myPage' is unable to navigate with Internal error: 500

Error log:
```
redmine_1     | I, [2020-01-03T03:59:13.236678 #1]  INFO -- : Started GET "/my/page" for 172.22.0.1 at 2020-01-03 03:59:13 +0000
redmine_1     | I, [2020-01-03T03:59:13.237354 #1]  INFO -- : Processing by MyController#page as HTML
redmine_1     | I, [2020-01-03T03:59:13.244610 #1]  INFO -- :   Current user: admin (id=1)
redmine_1     | I, [2020-01-03T03:59:13.246735 #1]  INFO -- :   Rendering my/page.html.erb within layouts/base
redmine_1     | I, [2020-01-03T03:59:13.269681 #1]  INFO -- :   Rendered my/page.html.erb within layouts/base (22.8ms)
redmine_1     | I, [2020-01-03T03:59:13.269847 #1]  INFO -- : Completed 500 Internal Server Error in 32ms (ActiveRecord: 7.2ms)
redmine_1     | F, [2020-01-03T03:59:13.270332 #1] FATAL -- :   
redmine_1     | F, [2020-01-03T03:59:13.270358 #1] FATAL -- : ActionView::Template::Error (wrong number of arguments (given 5, expected 4)):
redmine_1     | F, [2020-01-03T03:59:13.270442 #1] FATAL -- :     10: <div id="my-page" class="splitcontent">
redmine_1     |     11: <% @groups.each do |group| %>
redmine_1     |     12:   <div id="list-<%= group %>" class="block-receiver splitcontent<%= group %>">
redmine_1     |     13:     <%= render_blocks(@blocks[group], @user) %>
redmine_1     |     14:   </div>
redmine_1     |     15: <% end %>
redmine_1     |     16: </div>
redmine_1     | F, [2020-01-03T03:59:13.270464 #1] FATAL -- :   
redmine_1     | F, [2020-01-03T03:59:13.270487 #1] FATAL -- : plugins/redmine_more_filters/lib/redmine_more_filters/patches/query_patch.rb:181:in `sql_for_custom_field_with_more_filters'
redmine_1     | app/models/issue_query.rb:660:in `sql_for_project_status_field'
redmine_1     | plugins/redmine_more_filters/lib/redmine_more_filters/patches/query_patch.rb:286:in `block in statement_with_more_filters'
redmine_1     | plugins/redmine_more_filters/lib/redmine_more_filters/patches/query_patch.rb:221:in `each_key'
redmine_1     | plugins/redmine_more_filters/lib/redmine_more_filters/patches/query_patch.rb:221:in `statement_with_more_filters'
redmine_1     | app/models/issue_query.rb:329:in `issues'
redmine_1     | app/helpers/my_helper.rb:102:in `render_issuesassignedtome_block'
redmine_1     | app/helpers/my_helper.rb:64:in `render_block_content'
redmine_1     | app/helpers/my_helper.rb:35:in `render_block'
redmine_1     | app/helpers/my_helper.rb:27:in `block in render_blocks'
redmine_1     | app/helpers/my_helper.rb:26:in `each'
redmine_1     | app/helpers/my_helper.rb:26:in `render_blocks'
redmine_1     | app/views/my/page.html.erb:13:in `block in _app_views_my_page_html_erb___96863387556133507_47227918863200'
redmine_1     | app/views/my/page.html.erb:11:in `each'
redmine_1     | app/views/my/page.html.erb:11:in `_app_views_my_page_html_erb___96863387556133507_47227918863200'
redmine_1     | lib/redmine/sudo_mode.rb:65:in `sudo_mode'
redmine_1     | http://127.0.0.1/issues -> /my/page
redmine_1     | 172.22.0.1 - - [03/Jan/2020:03:59:18 UTC] "GET / HTTP/1.1" 200 11183
redmine_1     | http://127.0.0.1/issues -> /
redmine_1     | 172.22.0.1 - - [03/Jan/2020:03:59:21 UTC] "GET /projects HTTP/1.1" 200 20468
redmine_1     | http://127.0.0.1/ -> /projects
redmine_1     | 172.22.0.1 - - [03/Jan/2020:03:59:22 UTC] "GET /my/page HTTP/1.1" 500 648
```

Expectation:
The plugin should not cause 'myPage' down.

Thanks,

**Comment by HugoHasenbein** [comment]
Dear KexZh,

I may have found the culprit code, which is fixed in the latest release, now avalibale in GitHub

Thank you for your feedback

Best regards

Stephan

**Comment by HugoHasenbein** [comment]
Dear Kex,

has the fix solve the issue?

Best regards

Stephan

**Comment by gainskills** [comment]
Hi @HugoHasenbein , yes, the issue has been resolved. Thanks for your help.
Happy new year 😁
